
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 16 05:25:30 BRT 2023
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 11;
  public static final int IGUALIGUAL = 6;
  public static final int MENOR = 3;
  public static final int PTVIRG = 9;
  public static final int IDENT = 8;
  public static final int ABRECOLCH = 22;
  public static final int KW_IF = 14;
  public static final int MENORIGUAL = 5;
  public static final int PONTO = 24;
  public static final int MAIORIGUAL = 4;
  public static final int ABREPAR = 18;
  public static final int KW_DO = 16;
  public static final int FECHACOLCH = 23;
  public static final int MAIS = 10;
  public static final int ABRECHAVE = 20;
  public static final int NUMBER = 25;
  public static final int EOF = 0;
  public static final int MULT = 12;
  public static final int KW_WHILE = 17;
  public static final int DIV = 13;
  public static final int error = 1;
  public static final int MAIOR = 2;
  public static final int FECHACHAVE = 21;
  public static final int FECHAPAR = 19;
  public static final int KW_ELSE = 15;
  public static final int DIF = 7;
}

